### PR TITLE
adds python lesson from novice inflammation

### PR DESCRIPTION
**Pull request by katyhuff**
includes all the history. adds only the python directory and makes a conflict resolution with the .gitignore. Not yet converted to python 3. Ping @takluyver

### CODE REVIEW

**Comment by jiffyclub** [comment]
FYI don't wait on me to merge things, think ya'll have permission.

**Comment by katyhuff** [comment]
kthx!

**Comment by jiffyclub** [comment]
@katyhuff I think this broke the rendering of https://jiffyclub.github.io/2015-07-06-scipy/. In particular I think it moved all of the CSS and JS files. (It also added a .nojekyll file but I've already fixed that.)

**Comment by takluyver** [comment]
I'll see if I can fix this.

**Comment by takluyver** [comment]
The CSS is back now.

**Comment by jiffyclub** [comment]
Thanks!

**Comment by katyhuff** [comment]
ohh.... my bad. Thanks.

On Thu, Jun 25, 2015 at 11:30 AM, Matt Davis notifications@github.com
wrote:

> Thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jiffyclub/2015-07-06-scipy/pull/2#issuecomment-115355939
> .

## 

http://katyhuff.github.com

**Pull request merged**
